var random = require("random-js"),
    joke = [
        "If i had a dollar for every girl that found me unattractive, they would eventually find me attractive.",
        "I find it ironic that the colors red, white, and blue stand for freedom until they are flashing behind you.",
        "Apparently I snore so loudly that it scares everyone in the car I'm driving.",
        "I want to die peacefully in my sleep, like my grandfather.. Not screaming and yelling like the passengers in his car.",
        "Just read that 4,153,237 people got married last year, not to cause any trouble but shouldn't that be an even number?",
        "If I had a nickel for every time a homeless person asked me for change, I'd still say no.",
        "Isn't it great to live in the 21st century? Where deleting history has become more important than making it.",
        "I'm great at multitasking. I can waste time, be unproductive, and procrastinate all at once.",
        "If you think nobody cares whether you're alive, try missing a couple of payments.",
        "Nothing ruins a Friday more than an understanding that today is Tuesday.",
        "When an employment application asks who is to be notified in case of emergency, I always write, \"A very good doctor\".",
        "Some people say \"If you can't beat them, join them\". I say \"If you can't beat them, beat them\", because they will be expecting you to join them, so you will have the element of surprise.",
        "Two wrongs don't make a right, take your parents as an example.",
        "I eat my tacos over a Tortilla. That way when stuff falls out, BOOM, another taco.",
        "Why is it everything I love is either unhealthy, addicting or has multiple restraining orders against me?",
        "Your family tree must be a cactus because everybody on it is a prick.",
        "I bought a vacuum cleaner six months ago and so far all it's been doing is gathering dust.",
        "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
        "My favorite mythical creature? The honest politician.",
        "Artificial intelligence is no match for natural stupidity.",
        "My girlfriends dad asked me what I do. Apparently, \"your daughter\" wasn't the right answer.",
        "What's worse than waking up at a party and finding a penis drawn on your face? Finding out it was traced.",
        "I used to think I was indecisive, but now I'm not too sure.",
        "I can totally keep secrets. It's the people I tell them to that can't.",
        "Children in the back seats of cars cause accidents, but accidents in the back seats of cars cause children.",
        "Hospitality: making your guests feel like they're at home, even if you wish they were.",
        "Entered what I ate today into my new fitness app and it just sent an ambulance to my house.",
        "My internet is so slow, it's just faster to drive to the Google headquarters and ask them shit in person.",
        "I'm the kind of guy who stops the microwave at 1 second just to feel like a bomb defuser.",
        "When I get naked in the bathroom, the shower usually gets turned on.",
        "When I see ads on TV with smiling, happy housewives using a new cleaning product, the only thing I want to buy are the meds they must be on.",
        "According to most studies, people's number one fear is public speaking. Number two is death. Death is number two. Does that sound right? This means to the average person, if you go to a funeral, you're better off in the casket than doing the eulogy.",
        "I never wanted to believe that my Dad was stealing from his job as a road worker. But when I got home, all the signs were there.",
        "A roman legionaire went to a bar and held up two fingers. He then said 'Five beers please.'",
        "Where was Sally after the explosion? Everywhere.",
        "I didn't understand the math, so the teacher summed it up for me.",
        "Why did the baker ask for a loan? He kneeded the dough.",
        "My friend's bakery burned down last night. Now his business is toast.",
        "What's the difference between a piano and a fish? You can tuna piano, but you can't tuna fish!",
        "Working in a mirror factory is something I can totally see myself doing.",
        "I came up with a new word yesterday: Plagiarism.",
        "I just bought these shoes from my drug dealer. Don't know what he laced them with, but I've been tripping all day.",
        "How do you find Will Smith in the snow? Look for the fresh prints.",
        "What did the pirate say on his 80th birthday? Aye Matey",
        "What kind of bagel can fly? A plain bagel",
        "How many tickles does it take to make an octopus laugh? Ten tickles",
        "Where does the king keep his armies? In his sleevies",
        "A man walks into a zoo. The only animal in the entire zoo is a dog. It's a shitzhu.",
        "People say I'm condescending. That means I talk down to others.",
        "I took the shell off my racing snail, thinking it would make him run faster. If anything, it made him more sluggish.",
        "My friend gave me his Epi-Pen as he was dying. It seemed very important to him that I have it.",
        "A physicist sees a young man about to jump off the Empire State Building. He yells 'Don't do it! You have so much potential!'",
        "There are 10 types of people in this world - those who know binary, those who don't, and those who didn't expect this to be a base 3 joke.",
        "I wondered why the baseball was getting bigger. Then it hit me.",
        "I used to be a banker but I lost interest.",
        "Have you ever tried to eat a clock? It's very time consuming.",
        "I'm glad I know sign language, it's pretty handy.",
        "Yesterday I accidentally swallowed some food coloring. The doctor says I'm OK, but I feel like I've dyed a little inside.",
        "I don't trust these stairs because they're always up to something.",
        "The one who invented the door knocker got a No-bell prize.",
        "I used to have a fear of hurdles, but I got over it.",
        "There was once a cross-eyed teacher who couldn't control his pupils.",
        "A new type of broom came out, it is sweeping the nation.",
        "The experienced carpenter really nailed it, but the new guy screwed everything up.",
        "I once heard a joke about amnesia, but I forgot how it goes.",
        "I used to be addicted to soap, but I'm clean now.",
        "When a clock is hungry it goes back four seconds.",
        "The dead batteries were given out free of charge.",
        "Broken puppets for sale. No strings attached.",
        "Einstein developed a theory about space, and it was about time too.",
        "My new theory on inertia doesn't seem to be gaining momentum.",
        "Time flies like an arrow. Fruit flies like a banana.",
        "I can't believe I got fired from the calendar factory. All I did was take a day off.",
        "My first job was working in an orange juice factory, but I got canned: couldn't concentrate.",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "You can never lose a homing pigeon - if your homing pigeon doesn't come back, what you've lost is a pigeon.",
        "Whiteboards are remarkable.",
        "Camping is intense.",
        "My grandfather has the heart of a lion and a lifetime ban from the local zoo.",
        "What do you get when you cross a joke with a rhetorical question?",
        "I hate Russian dolls, they're so full of themselves.",
        "I tried making a pencil with an eraser at both ends but then I realised it was pointless.",
        "I couldn't work out how to fasten my seatbelt. Then it clicked.",
        "Never trust atoms, they make up everything.",
        "Where are average things made? In the satisfactory.",
        "I want to open a photo processing store in a developing country.",
        "I wasn't originally going to get a brain transplant, but then I changed my mind.",
        "The first time I used an elevator it was really uplifting, then it let me down.",
        "My phone has to wear glasses ever since it lost its contacts.", //TF2 Jokes Start
        "I would have gotten a Stout Shako, but I'm too refined.",
        "Why didn't the spy cross the road? Because he never really was on your side.",
        "How many snipers does it take to change a lightbulb? Only one, but tell that to the other three snipers.",
        "Why didn't the Sniper shave today? Because he never got his Razorback.",
        "How did the Heavy get to the point first? He was Russian.",
        "How long did it take for the Engi to create his buildings? A sentry.", //TF2 Jokes End
        "When the window fell into the incinerator, it was a pane in the ash to retrieve.",
        "The man who survived mustard gas and pepper spray is now a seasoned veteran.",
        "Police were called to a daycare where a three-year-old was resisting a rest.",
        "What is the difference between a nicely dressed man on a tricycle and a poorly dressed man on a bicycle? A tire.",
        "My wife told me to stop speaking in numbers, but I didn't 1 2.",
        "This girl said she recognised me from the vegetarian club, but I've never met herbivore.",
        "There is no I in DENIAL",
        "Cheese is grate for you.",
        "Why did the florist go out of business? Too many problems a rose.",
        "What do you call a scarecrow with a PhD? Outstanding in his field.",
        "Don't expect to eat something fancy when you're flying because it's plane food.",
        "What do mathematicians throw into their fireplaces? Natural Logs.",
        "He drove his expensive car into a tree and found out how the Mercedes bends.",
        "A bicycle can't stand on its own because it is two-tired.",
        "Why did the pig stop sunbathing? He was bacon in the heat.",
        "When the cannibal showed up late to the luncheon, they gave him the cold shoulder.",
        "It was an emotional wedding. Even the cake was in tiers.",
        "I was going to look for my missing watch, but I could never find the time.",
        "Novice pirates make terrible singers because they can't hit the high seas.",
        "If towels could tell jokes they would probably have a dry sense of humor.",
        "Two hats were hanging on a hat rack in the hallway. One hat says to the other, 'You stay here, I'll go on a head.'.",
        "I knew a woman who owned a taser, man was she stunning!",
        "Did you hear about the crime that happened in a parking garage? It was wrong on so many levels.",
        "There was a big paddle sale at the boat store. It was quite an oar deal.",
        "Did you hear about these new reversible jackets? I'm excited to see how they turn out.",
        "The magician got so mad he pulled his hare out.",
        "You know the problem with grapes these days. People just aren't raisin them right.",
        "Two peanuts were walking in a tough neighborhood and one of them was a-salted.",
        "My tailor is happy to make a pair of pants for me, or at least sew it seams.",
        "I should have been sad when my flashlight batteries died, but I was delighted.",
        "The lumberjack loved his new computer. He especially enjoyed logging in.",
        "Trust your calculator. It's something you can count on.",
        "Talking about computer hardware makes my mother board.",
        "Claustrophobic people are more productive thinking outside the box.",
        "Pencil sharpeners have a tough life - they live off tips.",
        "After manually rotating the heavy machinery, the worker grew very cranky.",
        "A butcher was trying so hard to be funny, but he just wasn't making the cut.",
        "When the wheel was invented, it caused a revolution.",
        "When crazy glue was invented lots of people became attached to it.",
        "Drinking too much coffee can cause a latte problems.",
        "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
        "I decide which beer to drink on a case by case basis.",
        "I was scrambling for another egg joke, but I can't seem to whip one up. Guess I'm a bit fried.",
        "Did you hear about the lost sausage? It was the missing link.",
        "I went to the store to buy some soup but they were out of stock.",
        "I relish the fact that you've mustard the strength to ketchup to me.",
        "I decided that becoming a vegetarian was a missed steak.",
        "When making butter there is little margarine for error.",
        "Bakers trade bread recipes on a knead to know basis.",
        "I ordered that a vault and speakers be delivered at my home yesterday. They arrived safe and sound.",
        "I bought a ton of staples and pushpins all for $3.99, plus tacks.",
        "The price of the big fan blew me away.",
        "Mr. Mushroom could never understand why he wasn't looked on as a real fun guy.",
        "My dog has a lot of potential, you just have to unleash it.",
        "The leopard was so good at guessing. Every time he was spot on.",
        "The divers had to be careful, the octopus was heavily armed.",
        "Puns about monorails always make for decent one-liners.",
        "A railroad engineer must be sure not to lose his train of thought or he might go down the wrong track.",
        "I'm not one for buoyancy but whatever floats your boat.",
        "He was arrested for throwing bombs from a boat, but they dropped the charges.",
        "I almost bought the last ticket to go on the sea, but that ship has sailed.",
        "What is the spy's least favorite aisle in the bakery? The pie-row",
        "What do you get when you burn a dollar bill? Legal Tinder. -rameys340",
        "My doctor gave a perscription for 'sex daily', but my girlfriend insists it says 'dyslexia' -chooch23"
    ];

module.exports = (statusReport) => {
    return {
        "triggers": ["joke"],
        "meta": {
            "name": "Joke",
            "usage": "&joke",
            "description": "Hear a funny joke, shitty pun, or an insightful one-liner."
        },
        "callback": (channelID, user, userID, message, msplit) => {
            var bot = require.main.exports.bot;
            var pick = random.pick(random.engines.nativeMath, joke);
            bot.sendMessage({
                to: channelID,
                message: pick
            });
        }
    };
};